### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by michaelblight** [originallyus/nodered-contrib-xiaomi-scale#4]
Greetings! I'm trying this for the first time and getting errors during install (see below). I see that you've done an update 20 minutes ago for "scale 2 support", so it might not be on npm yet (it doesn't look like you've bumped the version yet?).

I first installed it using the Palette, but then when I deploy I get an error showing "Error: Cannot find module 'bluetooth-hci-socket'". So I uninstalled it and retried with `sudo npm install nodered-contrib-xiaomi-scale`.

I'm using the docker Node Red image (version 1.1.2) on Ubuntu and have net=host. The container has node v10, whereas the host has v12. The bluetooth service is up and running on the host. Any help you can provide would be appreciated. 

This is the error I'm getting:

```
> usb@1.6.3 install /data/docker/node-red-host/data/node_modules/usb
> prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.5
prebuild-install info looking for cached prebuild @ /home/michaelblight/.npm/_prebuilds/f5a2d7-usb-v1.6.3-node-v72-linux-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /home/michaelblight/.npm/_prebuilds/f5a2d7-usb-v1.6.3-node-v72-linux-x64.tar.gz
prebuild-install info unpack resolved to /data/docker/node-red-host/data/node_modules/usb/build/Release/usb_bindings.node
prebuild-install info unpack required /data/docker/node-red-host/data/node_modules/usb/build/Release/usb_bindings.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> bluetooth-hci-socket@0.5.1 install /data/docker/node-red-host/data/node_modules/bluetooth-hci-socket
> node-gyp rebuild

make: Entering directory '/data/docker/node-red-host/data/node_modules/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
../src/BluetoothHciSocket.cpp: In static member function ‘static void BluetoothHciSocket::Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/BluetoothHciSocket.cpp:128:82: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction(’
   target->Set(Nan::New("BluetoothHciSocket").ToLocalChecked(), tmpl->GetFunction());
                                                                                  ^
In file included from /home/michaelblight/.cache/node-gyp/12.16.3/include/node/node.h:67:0,
                 from /home/michaelblight/.cache/node-gyp/12.16.3/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8.h:6126:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8.h:6126:46: note:   candidate expects 1 argument, 0 provided
../src/BluetoothHciSocket.cpp: In member function ‘void BluetoothHciSocket::poll()’:
../src/BluetoothHciSocket.cpp:251:95: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
                                                                                               ^
In file included from ../src/BluetoothHciSocket.cpp:8:0:
../../nan/nan.h:1047:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/BluetoothHciSocket.cpp: In member function ‘void BluetoothHciSocket::emitErrnoError()’:
../src/BluetoothHciSocket.cpp:269:109: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   Local<Function> errorConstructor = Local<Function>::Cast(globalObj->Get(Nan::New("Error").ToLocalChecked()));
                                                                                                             ^
In file included from /home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8-internal.h:14:0,
                 from /home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8.h:27,
                 from /home/michaelblight/.cache/node-gyp/12.16.3/include/node/node.h:67,
                 from /home/michaelblight/.cache/node-gyp/12.16.3/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8.h:3553:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^
/home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/BluetoothHciSocket.cpp:275:72: error: no matching function for call to ‘v8::Function::NewInstance(int, v8::Local<v8::Value> [1])’
   Local<Value> error = errorConstructor->NewInstance(1, constructorArgs);
                                                                        ^
In file included from /home/michaelblight/.cache/node-gyp/12.16.3/include/node/node.h:67:0,
                 from /home/michaelblight/.cache/node-gyp/12.16.3/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8.h:4281:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8.h:4281:44: note:   candidate expects 3 arguments, 2 provided
/home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8.h:4284:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8.h:4284:44: note:   candidate expects 1 argument, 2 provided
../src/BluetoothHciSocket.cpp:282:93: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
                                                                                             ^
In file included from ../src/BluetoothHciSocket.cpp:8:0:
../../nan/nan.h:1047:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/BluetoothHciSocket.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BluetoothHciSocket::BindRaw(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/BluetoothHciSocket.cpp:395:34: error: no matching function for call to ‘v8::Value::IntegerValue()’
       devId = arg0->IntegerValue();
                                  ^
In file included from /home/michaelblight/.cache/node-gyp/12.16.3/include/node/node.h:67:0,
                 from /home/michaelblight/.cache/node-gyp/12.16.3/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8.h:2705:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^~~~~~~~~~~~
/home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8.h:2705:40: note:   candidate expects 1 argument, 0 provided
../src/BluetoothHciSocket.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BluetoothHciSocket::BindUser(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/BluetoothHciSocket.cpp:417:34: error: no matching function for call to ‘v8::Value::IntegerValue()’
       devId = arg0->IntegerValue();
                                  ^
In file included from /home/michaelblight/.cache/node-gyp/12.16.3/include/node/node.h:67:0,
                 from /home/michaelblight/.cache/node-gyp/12.16.3/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8.h:2705:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^~~~~~~~~~~~
/home/michaelblight/.cache/node-gyp/12.16.3/include/node/v8.h:2705:40: note:   candidate expects 1 argument, 0 provided
binding.target.mk:111: recipe for target 'Release/obj.target/binding/src/BluetoothHciSocket.o' failed
make: *** [Release/obj.target/binding/src/BluetoothHciSocket.o] Error 1
make: Leaving directory '/data/docker/node-red-host/data/node_modules/bluetooth-hci-socket/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/docker/node-red-host/data/node_modules/bluetooth-hci-socket
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/noble/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN multiple-select@1.5.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ nodered-contrib-xiaomi-scale@0.0.3
added 5 packages from 5 contributors and audited 130 packages in 3.208s
```

**Comment by michaelblight** [comment]
I uninstalled and reinstalled from github using
```
sudo npm install git+https://github.com/originallyus/nodered-contrib-xiaomi-scale.git
```
Then I don't seem to get the same errors. However, when deploying a flow containing the node I get the following error:
```
Error: The module '/data/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'was compiled against a different Node.js version using NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 64. Please try re-compiling or re-installingthe module (for instance, using `npm rebuild` or `npm install`).
```
Note also that I'm running this on a NUC which has bluetooth built-in (ie. not a USB dongle).

**Comment by torinnguyen** [comment]
We have not published a new version to 'npm' although there's new merge.
Even when you do "sudo npm install nodered-contrib-xiaomi-scale", it is still the old version.

The error your are seeing is not related to our xiaomi-scale node.
It is a common error with "node-gyp rebuild" process as mentioned in bluetooth-hci-socket [README](https://github.com/noble/node-bluetooth-hci-socket):
node-gyp is only required if the npm cannot find binary for your OS version otherwise the binaries are prebuilt.

It's probably just that since you're running docker

**Comment by torinnguyen** [comment]
> I uninstalled and reinstalled from github using
> 
> ```
> sudo npm install git+https://github.com/originallyus/nodered-contrib-xiaomi-scale.git
> ```
> 
> Then I don't seem to get the same errors. However, when deploying a flow containing the node I get the following error:
> 
> ```
> Error: The module '/data/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'was compiled against a different Node.js version using NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 64. Please try re-compiling or re-installingthe module (for instance, using `npm rebuild` or `npm install`).
> ```
> 
> Note also that I'm running this on a NUC which has bluetooth built-in (ie. not a USB dongle).

Same as the previous comment.
This has nothing to do with our node.

**Comment by michaelblight** [comment]
Thanks for the update - so to confirm, after installing the node from the palette I'm getting "Cannot find module 'bluetooth-hci-socket'". And if I install with npm I get other errors. I'm confused about what to do next.

**Comment by torinnguyen** [comment]
Please try to install 'bluetooth-hci-socket' module manually first. Once that succeeds, try to install xiaomi-scale.

**Comment by michaelblight** [comment]
I tried that but it didn't work. Googling the errors I got suggested downgrading node to v8. I did this on the host and then re-installed, which worked, but I'm not sure what the implications are. However, then when I install and use xiaomi-scale using the palette, I get the following error:
```
Error: The module '/data/node_modules/bluetooth-hci-socket/build/Release/binding.node'
was compiled against a different Node.js version using NODE_MODULE_VERSION 57. 
This version of Node.js requires NODE_MODULE_VERSION 64. 
Please try re-compiling or re-installingthe module (for instance, using `npm rebuild` or `npm install`).
```
